language: generic
cache: cocoapods
before_install:
  - git submodule add https://${GITHUB_KEY}@github.com/mopub/ios-mediation.git
  - git submodule update --init --recursive
  - npm i -g grunt-cli
  - npm i -g firebase-tools@latest
  - gem install cocoapods
  - pod repo update
script:
  - chmod 777 ./ios-mediation/scripts/ios_automate_release.sh
  - ./ios-mediation/scripts/ios_automate_release.sh
# branch whitelist
branches:
  only:
  - master
